name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Railway CLI
      run: |
        curl -fsSL https://railway.com/install.sh | sh
        railway --version

    - name: Link project with Railway
      run: |
        railway link -p ${{ secrets.RAILWAY_API_KEY }}

    - name: Deploy to Railway
      run: |
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

